// <auto-generated />
using System;
using FlowCast.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowCast.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlowCastContext))]
    partial class FlowCastContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowCast.Core.Domain.Entities.PredictionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Values")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PredictionDatas", (string)null);
                });

            modelBuilder.Entity("FlowCast.Core.Domain.Entities.PredictionResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("PredictionDataId")
                        .HasColumnType("int");

                    b.Property<int>("PredictionMode")
                        .HasColumnType("int");

                    b.Property<decimal>("Results")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PredictionDataId");

                    b.ToTable("PredictionResults", (string)null);
                });

            modelBuilder.Entity("FlowCast.Core.Domain.Entities.PredictionResults", b =>
                {
                    b.HasOne("FlowCast.Core.Domain.Entities.PredictionData", "PredictionData")
                        .WithMany("PredictionResults")
                        .HasForeignKey("PredictionDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PredictionData");
                });

            modelBuilder.Entity("FlowCast.Core.Domain.Entities.PredictionData", b =>
                {
                    b.Navigation("PredictionResults");
                });
#pragma warning restore 612, 618
        }
    }
}
